import sys
from collections.abc import Callable, Iterable, Iterator, Mapping, Sequence
from types import TracebackType
from typing import Any, Literal, ParamSpec, TypeAlias, TypeVar, final

from cysqlite.metadata import Column, ColumnMetadata, ForeignKey, Index, View

if sys.version_info >= (3, 12):
    from collections.abc import Buffer
else:
    from typing_extensions import Buffer

if sys.version_info >= (3, 11):
    from typing import Self
else:
    from typing_extensions import Self

_SqliteData: TypeAlias = str | Buffer | int | float | None
_AdaptedInputData: TypeAlias = _SqliteData | Any
_Parameters: TypeAlias = Sequence[_AdaptedInputData] | Mapping[str, _AdaptedInputData]
_IsolationLevel: TypeAlias = Literal["DEFERRED", "EXCLUSIVE", "IMMEDIATE"] | None

T = TypeVar("T")
P = ParamSpec("P")

threadsafety: int
SENTINEL: object

class _callable_context_manager:
    def __call__(self, fn: Callable[P, T]) -> Callable[P, T]: ...

class Row:
    def __getitem__(self, key: str | int) -> Any: ...
    def __contains__(self, key: str | int) -> bool: ...
    def get(self, key: str | int, default=...) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __hash__(self) -> int: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[Any]: ...
    def items(self) -> list[tuple[str, Any]]: ...
    def as_dict(self) -> dict[str, Any]: ...

@final
class Cursor:
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        type: type[BaseException] | None,
        value: BaseException | None,
        traceback: TracebackType | None,
    ): ...
    def execute(self, sql: str, params: _Parameters | None = None) -> Self: ...
    def executemany(
        self, sql: str, params: Sequence[_Parameters] | None = None
    ) -> Self: ...
    def executescript(self, sql: str) -> Self: ...
    def __iter__(self) -> Self: ...
    def __next__(self) -> tuple[Any, ...]: ...
    def close(self) -> None: ...
    def fetchone(self) -> tuple[Any, ...] | None: ...
    def fetchall(self) -> list[Any | tuple]: ...
    def scalar(self) -> Any: ...
    def columns(self) -> list[Any]: ...

@final
class Connection(_callable_context_manager):
    def __init__(
        self,
        database: str,
        flags: int | None = None,
        timeout: float = 5.0,
        vfs: str | None = None,
        uri: bool = False,
        cached_statements: int = 100,
        extensions: bool = True,
        row_factory: Callable[..., "Row"] | None = None,
        autoconnect: bool = True,
        pragmas: Any = ...,
    ) -> None: ...
    def finalize_statements(self) -> None: ...
    def close(self) -> bool: ...
    def connect(self) -> bool: ...
    def is_closed(self) -> bool: ...
    def get_stmt_usage(self) -> tuple[int, int]: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> bool | None: ...
    @property
    def callback_error(self) -> BaseException | None: ...
    def cursor(self) -> Cursor: ...
    def execute(self, sql: str, params: _Parameters | None = ...) -> Cursor: ...
    def executemany(
        self, sql: str, seq_of_params: Sequence[_Parameters] | None = None
    ) -> Cursor: ...
    def executescript(self, sql: str) -> Cursor: ...
    def execute_one(
        self, sql: str, params: _Parameters | None = ...
    ) -> tuple[Any, ...] | None: ...
    def execute_scalar(self, sql: str, params: _Parameters | None = ...) -> None: ...
    def execute_simple(self, sql: str, callback: Callable[..., Any] = ...) -> None: ...
    def begin(self, lock: _IsolationLevel = None) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def changes(self) -> int: ...
    def total_changes(self) -> int: ...
    def last_insert_rowid(self) -> int: ...
    def interrupt(self) -> None: ...
    def autocommit(self) -> int: ...
    @property
    def in_transaction(self) -> bool: ...
    def status(self, flag: int) -> tuple[int, int]: ...
    def pragma(
        self,
        key: str,
        value: Any = ...,
        database: str | None = None,
        multi: bool = False,
    ) -> None: ...
    def get_tables(self, database: str | None = None) -> list["Row"]: ...
    def get_views(self, database: str | None = None) -> list[View]: ...
    def get_indexes(self, table: str, database: str | None = None) -> list[Index]: ...
    def get_columns(self, table: str, database: str | None = None) -> list[Column]: ...
    def get_primary_keys(
        self, table: str, database: str | None = None
    ) -> list[str]: ...
    def get_foreign_keys(
        self, table: str, database: str | None = None
    ) -> list[ForeignKey]: ...
    def table_column_metadata(
        self, table: str | bytes, column: str | bytes, database: str | None = None
    ) -> ColumnMetadata: ...
    def transaction(self, lock: _IsolationLevel = None) -> Transaction: ...
    def savepoint(self, sid: str | None = None) -> Savepoint: ...
    def atomic(self, lock: _IsolationLevel = None) -> Atomic: ...
    def backup(
        self,
        dest: "Connection",
        pages: int | None = None,
        name: str | None = None,
        progress: Callable[[int, int, bool], None] | None = None,
        src_name: str | None = None,
    ) -> None: ...
    def backup_to_file(
        self,
        filename: str,
        pages: int | None = None,
        name: str | None = None,
        progress: Callable[[int, int, bool], None] | None = None,
        src_name: str | None = None,
    ) -> None: ...
    def blob_open(
        self,
        table: str,
        column: str,
        rowid: int,
        read_only: bool = False,
        database: str | None = None,
    ) -> Blob: ...
    def register_converter(
        self, data_type: type[Any], fn: Callable[..., Any]
    ) -> None: ...
    def unregister_converter(self, data_type: type[Any]) -> bool: ...
    def converter(
        self, data_type: Callable[P, T]
    ) -> Callable[[Callable[P, T]], Callable[P, T]]: ...
    def load_extension(self, name: str) -> None: ...
    def create_function(self, fn, name=..., nargs=..., deterministic=...) -> None: ...
    def create_aggregate(self, agg, name=..., nargs=..., deterministic=...) -> None: ...
    def create_window_function(
        self, agg, name=..., nargs=..., deterministic=...
    ) -> None: ...
    def create_collation(self, fn: Callable[..., Any], name=...) -> None: ...
    def commit_hook(self, fn: Callable[..., Any]) -> None: ...
    def rollback_hook(self, fn: Callable[..., Any]) -> None: ...
    def update_hook(self, fn: Callable[..., Any]) -> None: ...
    def authorizer(self, fn: Callable[..., Any]) -> None: ...
    def trace(self, fn: Callable[..., Any], mask: int = 2) -> None: ...
    def progress(self, fn: Callable[[int, int, bool], None], n: int = 1) -> None: ...
    def set_busy_handler(self, timeout: float = 5.0) -> None: ...
    def optimize(
        self,
        debug: bool = False,
        run_tables: bool = True,
        set_limit: bool = True,
        check_table_sizes: bool = False,
        dry_run: bool = False,
    ) -> Cursor: ...
    def attach(self, filename: str, name: str) -> None: ...
    def detach(self, name: str) -> None: ...
    def database_list(self) -> list[tuple]: ...
    def set_main_db_name(self, name: str) -> None: ...
    def db_config(self, op, setting=...) -> int: ...
    def set_foreign_keys_enabled(self, enabled: int) -> int: ...
    def get_foreign_keys_enabled(self) -> int: ...
    def set_triggers_enabled(self, enabled: int) -> int: ...
    def get_triggers_enabled(self) -> int: ...
    def set_load_extension(self, enabled: int) -> int: ...
    def get_load_extension(self) -> int: ...
    def set_shared_cache(self, enabled: int) -> int: ...
    def set_autocheckpoint(self, n: int) -> None: ...
    def checkpoint(
        self, full=..., truncate=..., restart=..., name=...
    ) -> tuple[int, int]: ...
    def setlimit(self, category, limit: int) -> int: ...
    def getlimit(self, category) -> int: ...
    def file_control(self, op: int, val: int, name=...) -> int: ...

class Transaction(_callable_context_manager):
    def __init__(self, conn: Connection, lock: _IsolationLevel = None) -> None: ...
    def _begin(self) -> None: ...
    def commit(self, begin: bool = True) -> None: ...
    def rollback(self, begin: bool = True) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        type: type[BaseException] | None,
        value: BaseException | None,
        traceback: TracebackType | None,
    ): ...

class Savepoint(_callable_context_manager):
    def __init__(self, conn: Connection, sid: str | None = None) -> None: ...
    def _begin(self) -> None: ...
    def commit(self, begin: bool = True) -> None: ...
    def rollback(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        type: type[BaseException] | None,
        value: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool | None: ...

class Atomic(_callable_context_manager):
    def __init__(self, conn: Connection, lock: _IsolationLevel = None) -> None: ...
    def __enter__(self) -> Transaction | Savepoint: ...
    def __exit__(
        self,
        type: type[BaseException] | None,
        value: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool | None: ...

class Blob:
    def __init__(
        self,
        conn: Connection,
        table: str,
        column: str,
        rowid: int,
        read_only: bool = ...,
        database: str | None = None,
    ) -> None: ...
    @property
    def closed(self): ...
    def close(self) -> None: ...
    def reopen(self, rowid: int) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        type: type[BaseException] | None,
        value: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool | None: ...
    def fileno(self): ...
    def flush(self) -> None: ...
    def isatty(self) -> bool | None: ...
    def readable(self) -> bool: ...
    def writable(self) -> bool: ...
    def seekable(self) -> bool: ...
    def truncate(self, size: int = ...): ...
    def __iter__(self) -> Self: ...
    def __next__(self) -> bytes: ...
    def readline(self, size: int = ...) -> bytes: ...
    def readlines(self, hint=...) -> list[bytes]: ...
    def writelines(self, lines: Iterable[bytes]) -> int: ...
    def read(self, size: int = ...) -> bytes: ...
    def readall(self) -> bytes: ...
    def readinto(self, b) -> int: ...
    def write(self, data: bytes) -> int: ...
    def seek(self, offset: int, whence: int = ...) -> int: ...
    def tell(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: int) -> int | bytes: ...
    def __setitem__(self, key: int, value: int) -> None: ...

def connect(
    database: str,
    flags: int | None = None,
    timeout: float = 5.0,
    vfs: Any | None = None,
    uri: bool = False,
    cached_statements: int = 100,
    extensions: bool = True,
    row_factory: Callable[..., Row] = None,
    autoconnect: bool = True,
    pragmas: Any | None = None,
) -> Connection: ...
def status(flag: int) -> tuple[int, int]: ...
def set_singlethread() -> bool: ...
def set_multithread() -> bool: ...
def set_serialized() -> bool: ...
def set_lookaside(size: int, slots: int) -> bool: ...
def set_mmap_size(default_size: int, max_size: int) -> bool: ...
def set_stmt_journal_spill(nbytes: int) -> bool: ...
def compile_option(opt: str | bytes) -> int: ...
def vfs_list() -> list[str]: ...
def rank_lucene(py_match_info: Buffer, *raw_weights: int) -> float: ...
def rank_bm25(py_match_info: Buffer, *raw_weights: int) -> float: ...
def damerau_levenshtein_dist(s1: str, s2: str) -> int: ...
def levenshtein_dist(a: str, b: str) -> int: ...

class median(object):
    def __init__(self): ...
    def step(self, item: int | float) -> None: ...
    def inverse(self, item: int | float) -> None: ...
    def finalize(self) -> int | float: ...
    def value(self) -> int | float: ...
