#!/usr/bin/env python
"""
Fetch the SQLite3 Multiple Ciphers amalgamation, renamed to sqlite3.c and
sqlite3.h in the repository root.

Usage: fetch_sqlite3mc [tag]

With no argument the latest release is fetched. With a tag, e.g. "v2.5.0",
that release is fetched instead.
"""
from urllib.request import urlopen
import json
import os
import shutil
import sys
import tempfile
import zipfile


CUR_DIR = os.path.dirname(__file__)
RELEASES = 'https://api.github.com/repos/utelle/SQLite3MultipleCiphers/releases'

RENAMES = {
    'sqlite3mc_amalgamation.c': 'sqlite3.c',
    'sqlite3mc_amalgamation.h': 'sqlite3.h'}


def find_release(tag=None):
    url = '%s/tags/%s' % (RELEASES, tag) if tag else '%s/latest' % RELEASES
    try:
        with urlopen(url) as fh:
            release = json.load(fh)
    except Exception as exc:
        raise RuntimeError('Could not fetch sqlite3mc release info: %s' % exc)

    for asset in release.get('assets', ()):
        if asset['name'].endswith('-amalgamation.zip'):
            return asset['name'], asset['browser_download_url']
    raise RuntimeError('No amalgamation asset in release %s.'
                       % release.get('tag_name', tag))


def download(name, url):
    with tempfile.NamedTemporaryFile(suffix='.zip') as tmp:
        print('Downloading %s' % name)
        with urlopen(url) as fh:
            shutil.copyfileobj(fh, tmp)
        tmp.seek(0)
        with zipfile.ZipFile(tmp) as zf:
            for path in zf.namelist():
                filename = RENAMES.get(os.path.basename(path))
                if filename is None:
                    continue

                dest = os.path.join(CUR_DIR, '../', filename)
                with zf.open(path) as src, open(dest, 'wb') as fh_out:
                    shutil.copyfileobj(src, fh_out)
                print('Wrote %s' % os.path.abspath(dest))


if __name__ == '__main__':
    tag = sys.argv[1] if len(sys.argv) > 1 else None
    download(*find_release(tag))
